cd(path)
load('training_info.mat')
value{i,4} = [ 'Training Runtime: ' num2str(Runtime) ' , Terminating min(rob): ' num2str(rho_min) ];
subplot(5,4,(i-1)*4+4)
load(['RP_reviewer_Controller_init' num2str(i) '_LB4TL.mat']) %%% This file will be automatically generated by the above py file.
plotting(net)
axis equal
if i==1
    title('LB4TL')
end
clc